CmsBundle\Entity\Accueil:
    type: entity
    table: null
    repositoryClass: CmsBundle\Repository\AccueilRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
            column: Titre
        premiertitre:
            type: string
            length: 255
            column: premierTitre
        premiercontenu:
            type: text
            column: premierContenu
        deuxiemetitre:
            type: string
            length: 255
            column: deuxiemeTitre
        deuxiemecontenu:
            type: text
            column: deuxiemeContenu
        troisiemetitre:
            type: string
            length: 255
            column: troisiemeTitre
        troisiemecontenu:
            type: text
            column: troisiemeContenu
        image:
            type: string
            length: 255
            nullable: true
            column: Image
        contenu:
            type: text
            column: Contenu
        langue:
            type: string
            lenght: 2
            column: langue
        langue_active:
            type: boolean

    lifecycleCallbacks:
        prePersist: [ preUpload, setCreatedAtValue, setExpiresAtValue ]
        preUpdate: [ preUpload, setUpdatedAtValue ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]

    oneToMany:
        accueil:
            targetEntity: CmsBundle\Entity\Accueil
            mappedBy: accueil
            cascade:   [persist]

