CmsBundle\Entity\Commercant:
    type: entity
    table: null
    repositoryClass: CmsBundle\Repository\CommercantRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        image:
            type: string
            length: 255
            column: image
            nullable: true
        adresse:
            type: string
            length: 255
        nom:
            type: string
            length: 255
        code:
            type: integer
        ville:
            type: string
            length: 255
        lien:
            type: string
            lenght: 255
            nullable: true
    lifecycleCallbacks:
          prePersist: [ preUpload, setCreatedAtValue, setExpiresAtValue ]
          preUpdate: [ preUpload, setUpdatedAtValue ]
          postPersist: [ upload ]
          postUpdate: [ upload ]
          postRemove: [ removeUpload ]
