mobile_mobilelist:
    resource: "@MobileBundle/Resources/config/routing/mobilelist.yml"
    prefix:   /admin/mobilelist

mobile_homepage:
    path:     /mobile
    defaults: { _controller: MobileBundle:Default:getJson }
    methods:  GET
