mobile_mobilelist:
    resource: "@MobileBundle/Resources/config/routing/mobilelist.yml"
    prefix:   /admin/mobilelist

mobile_homepage:
    path:     /
    defaults: { _controller: MobileBundle:Default:index }
