cms_accueil:
    resource: "@CmsBundle/Resources/config/routing/accueil.yml"
    prefix:   /admin/accueil

cms_artiste:
    resource: "@CmsBundle/Resources/config/routing/artiste.yml"
    prefix:   /admin/artiste

cms_commercant:
    resource: "@CmsBundle/Resources/config/routing/commercant.yml"
    prefix:   /admin/commercant

cms_partenaire:
    resource: "@CmsBundle/Resources/config/routing/partenaire.yml"
    prefix:   /admin/partenaire

cms_presse:
    resource: "@CmsBundle/Resources/config/routing/presse.yml"
    prefix:   /admin/presse

cms_categorie:
    resource: "@CmsBundle/Resources/config/routing/categorie.yml"
    prefix:   /admin/categorie

cms_newsletter:
    resource: "@CmsBundle/Resources/config/routing/newsletters.yml"
    prefix:    /admin/newsletter

cms_admin_equipe:
    resource: "@CmsBundle/Resources/config/routing/equipe.yml"
    prefix:   /admin/equipe

cms_admin_apropos:
    resource: "@CmsBundle/Resources/config/routing/apropos.yml"
    prefix:   /admin/apropos

cms_admin_youtube:
    resource: "@CmsBundle/Resources/config/routing/youtube.yml"
    prefix:   /admin/youtube

user:
    resource: "@CmsBundle/Resources/config/routing/user.yml"
    prefix:   /

cms_contact:
    path: /send
    defaults: { _controller: CmsBundle:Contact:send }
    methods: [POST, GET]

cms_homepage:
    path:     /
    defaults: { _controller: CmsBundle:User:index }

cms_admin:
    path:     /admin
    defaults: { _controller: CmsBundle:Admin:index }

