partenaire_index:
    path:     /
    defaults: { _controller: "CmsBundle:Partenaire:index" }

partenaire_new:
    path:     /new
    defaults: { _controller: "CmsBundle:Partenaire:new" }
    methods:  [GET, POST]

partenaire_edit:
    path:     /{id}/edit
    defaults: { _controller: "CmsBundle:Partenaire:edit" }
    methods:  [GET, POST]

partenaire_delete:
    path:     /{id}/delete
    defaults: { _controller: "CmsBundle:Partenaire:delete" }
    requirements:
        id:  \d+


